import type { Country, Option } from './types';

export const ALL_COUNTRIES: Country[] = [
  // EU Countries
  { name: 'Austria', category: 'EU' },
  { name: 'Belgio', category: 'EU' },
  { name: 'Bulgaria', category: 'EU' },
  { name: 'Cipro', category: 'EU' },
  { name: 'Croazia', category: 'EU' },
  { name: 'Danimarca', category: 'EU' },
  { name: 'Estonia', category: 'EU' },
  { name: 'Finlandia', category: 'EU' },
  { name: 'Francia', category: 'EU' },
  { name: 'Germania', category: 'EU' },
  { name: 'Grecia', category: 'EU' },
  { name: 'Irlanda', category: 'EU' },
  { name: 'Islanda', category: 'EU' },
  { name: 'Lettonia', category: 'EU' },
  { name: 'Liechtenstein', category: 'EU' },
  { name: 'Lituania', category: 'EU' },
  { name: 'Lussemburgo', category: 'EU' },
  { name: 'Malta', category: 'EU' },
  { name: 'Norvegia', category: 'EU' },
  { name: 'Paesi Bassi', category: 'EU' },
  { name: 'Polonia', category: 'EU' },
  { name: 'Portogallo', category: 'EU' },
  { name: 'Regno Unito', category: 'EU' }, // Often grouped with EU for roaming
  { name: 'Repubblica Ceca', category: 'EU' },
  { name: 'Romania', category: 'EU' },
  { name: 'Slovacchia', category: 'EU' },
  { name: 'Slovenia', category: 'EU' },
  { name: 'Spagna', category: 'EU' },
  { name: 'Svezia', category: 'EU' },
  { name: 'Svizzera', category: 'EU' }, // Often grouped with EU for roaming
  { name: 'Ungheria', category: 'EU' },

  // USA
  { name: 'Stati Uniti', category: 'USA' },

  // TOP16 Countries (which are also ExtraUE_World)
  { name: 'Argentina', category: 'TOP16' },
  { name: 'Australia', category: 'TOP16' },
  { name: 'Brasile', category: 'TOP16' },
  { name: 'Canada', category: 'TOP16' },
  { name: 'Cina', category: 'TOP16' },
  { name: 'Emirati Arabi Uniti', category: 'TOP16' },
  { name: 'Giappone', category: 'TOP16' },
  { name: 'Hong Kong', category: 'TOP16' },
  { name: 'India', category: 'TOP16' },
  { name: 'Israele', category: 'TOP16' },
  { name: 'Russia', category: 'TOP16' },
  { name: 'Sudafrica', category: 'TOP16' },
  { name: 'Thailandia', category: 'TOP16' },
  { name: 'Turchia', category: 'TOP16' },
  { name: 'Ucraina', category: 'TOP16' },

  // ExtraUE_World
  { name: 'Albania', category: 'ExtraUE_World' },
  { name: 'Algeria', category: 'ExtraUE_World' },
  { name: 'Bermuda', category: 'ExtraUE_World' },
  { name: 'Chad', category: 'ExtraUE_World' },
  { name: 'Congo', category: 'ExtraUE_World' },
  { name: 'Cuba', category: 'ExtraUE_World' },
  { name: 'Egitto', category: 'ExtraUE_World' },
  { name: 'Filippine', category: 'ExtraUE_World' },
  { name: 'Gambia', category: 'ExtraUE_World' },
  { name: 'Indonesia', category: 'ExtraUE_World' },
  { name: 'Kosovo', category: 'ExtraUE_World' },
  { name: 'Lesotho', category: 'ExtraUE_World' },
  { name: 'Maldive', category: 'ExtraUE_World' },
  { name: 'Marocco', category: 'ExtraUE_World' },
  { name: 'Mauritania', category: 'ExtraUE_World' },
  { name: 'Messico', category: 'ExtraUE_World' },
  { name: 'Polinesia Francese', category: 'ExtraUE_World' },
  { name: 'Reunion', category: 'ExtraUE_World' },
  { name: 'Seychelles', category: 'ExtraUE_World' },
  { name: 'Somalia', category: 'ExtraUE_World' },
  { name: 'Tunisia', category: 'ExtraUE_World' },
  
  // Excluded from Roaming Mondo New
  { name: 'Kyrgyzstan', category: 'Excluded_MondoNew' },
  { name: 'Palestina', category: 'Excluded_MondoNew' },
  { name: 'Turkmenistan', category: 'Excluded_MondoNew' },
  { name: 'Andorra', category: 'Excluded_MondoNew' },
  { name: 'Isole Far Oer', category: 'Excluded_MondoNew' },
  { name: 'Groenlandia', category: 'Excluded_MondoNew' },
  { name: 'Vanuatu', category: 'Excluded_MondoNew' },
  { name: 'Cambogia', category: 'Excluded_MondoNew' },
  { name: 'New Caledonia', category: 'Excluded_MondoNew' },
  { name: 'Burundi', category: 'Excluded_MondoNew' },
  { name: 'Gibuti', category: 'Excluded_MondoNew' },
  { name: 'Eritrea', category: 'Excluded_MondoNew' },
  { name: 'Etiopia', category: 'Excluded_MondoNew' },
  { name: 'Guinea', category: 'Excluded_MondoNew' },
  { name: 'Guinea Bissau', category: 'Excluded_MondoNew' },
  { name: 'Guinea Equatoriale', category: 'Excluded_MondoNew' },
  { name: 'Iran', category: 'Excluded_MondoNew' },
  { name: 'Libano', category: 'Excluded_MondoNew' },
  { name: 'Libia', category: 'Excluded_MondoNew' },
  { name: 'Madagascar', category: 'Excluded_MondoNew' },
  { name: 'Mozambico', category: 'Excluded_MondoNew' },
  { name: 'Malawi', category: 'Excluded_MondoNew' },
  { name: 'Sudan', category: 'Excluded_MondoNew' },
  { name: 'Togo', category: 'Excluded_MondoNew' },
  { name: 'Yemen', category: 'Excluded_MondoNew' },
  { name: 'Zambia', category: 'Excluded_MondoNew' },
  { name: 'Zimbabwe', category: 'Excluded_MondoNew' },
];

export const ALL_OPTIONS: Option[] = [
  {
    id: 'tim-stati-uniti',
    name: 'TIM Stati Uniti',
    type: 'monthly',
    cost: '12€',
    costUnit: 'mese',
    description: "L'opzione ideale e più conveniente per i tuoi viaggi di lavoro negli USA.",
    includes: {
      callsOriginated: 'Illimitate (da USA verso USA, Europa e Italia)',
      callsReceived: 'Illimitate (in USA)',
      sms: 'Illimitati (da USA)',
      data: '5 GB (in USA)',
      internationalCalls: "1000 minuti (dall'Italia verso USA)",
    },
    coverage: { type: 'category', category: 'USA' },
    notes: 'Prezzo in promozione, anziché 30€/mese. Overfranchigia dati molto bassa.',
    isRecommended: true,
  },
  {
    id: 'roaming-monthly-top',
    name: 'Roaming Monthly TOP',
    type: 'monthly',
    cost: '35€',
    costUnit: 'mese',
    description: 'Copertura mensile completa per i 16 paesi Extra UE più frequentati.',
    includes: {
      callsOriginated: 'Illimitate (dai 16 Paesi verso i 16 Paesi e Italia). Es: Chiami dalla Cina verso un numero italiano o australiano.',
      callsReceived: 'Illimitate (nei 16 Paesi)',
      sms: 'Illimitati (dai 16 Paesi)',
      data: '5 GB (nei 16 Paesi). Es: Usi la navigazione GPS in Canada.',
      internationalCalls: "1000 minuti (dall'Italia verso i 16 Paesi). Es: Chiami dall'Italia verso un numero in Brasile.",
    },
    coverage: { type: 'category', category: 'TOP16' },
    notes: 'Paesi inclusi: Argentina, Australia, Brasile, Canada, Cina, Emirati Arabi Uniti, Giappone, Hong Kong, India, Israele, Russia, Stati Uniti, Sudafrica, Thailandia, Turchia, Ucraina.',
    isRecommended: true,
  },
  {
    id: 'roaming-mondo-new',
    name: 'Roaming Mondo New',
    type: 'monthly',
    cost: '50€',
    costUnit: 'mese',
    description: 'Copertura mensile per la maggior parte dei paesi Extra UE.',
    includes: {
      callsOriginated: "500 min (da Extra UE verso tutto il Mondo). Es: Chiami dalle Filippine verso l'Italia.",
      callsReceived: '500 min (in Extra UE)',
      sms: '500 SMS (da Extra UE)',
      data: '5 GB (in Extra UE). Es: Navighi su internet in Indonesia.',
    },
    coverage: { type: 'category', category: 'ExtraUE_World' },
    notes: 'Esclude una lista specifica di paesi e il traffico satellitare/marittimo/in volo. Ideale per viaggi multi-paese fuori dalle zone TOP.',
  },
  {
    id: 'executive-class-2-0',
    name: 'Executive Class 2.0',
    type: 'weekly',
    cost: '40€',
    costUnit: 'settimana',
    description: 'Opzione flessibile con canone mensile per chiamate internazionali e un gettone settimanale che si attiva solo quando sei in Extra UE.',
    includes: {
      callsOriginated: '500 min/settimana (da Extra UE verso tutto il Mondo). Es: Sei in Indonesia e chiami un cliente nelle Filippine.',
      callsReceived: '500 min/settimana (in Extra UE)',
      sms: '1000 SMS/settimana (in Extra UE)',
      data: '2 GB/settimana (in Extra UE)',
      internationalCalls: 'Canone fisso mensile (30€) include: 1000 min/mese da Italia vs Mondo e 1000 min/mese da UE vs Extra UE. Es: Chiami dall\'ufficio in Italia verso un fornitore in Marocco.',
    },
    coverage: { type: 'category', category: 'ExtraUE_World' },
    notes: "Il gettone settimanale da 40€ si attiva automaticamente al primo utilizzo (chiamata, SMS, dati) in un paese Extra UE e dura 7 giorni.",
  },
  {
    id: 'roaming-weekly-top',
    name: 'Roaming Weekly TOP',
    type: 'weekly',
    cost: '35€',
    costUnit: 'settimana',
    description: 'Gettone settimanale per i 16 paesi Extra UE più frequentati.',
    includes: {
      callsOriginated: '250 min (dai 16 Paesi)',
      callsReceived: '250 min (nei 16 Paesi)',
      sms: '500 SMS (dai 16 Paesi)',
      data: '500 MB (nei 16 Paesi)',
    },
    coverage: { type: 'category', category: 'TOP16' },
    notes: 'Si attiva solo se utilizzata. Paesi inclusi: Argentina, Australia, Brasile, Canada, Cina, Emirati Arabi Uniti, Giappone, Hong Kong, India, Israele, Russia, Stati Uniti, Sudafrica, Thailandia, Turchia, Ucraina.',
  },
  {
    id: 'roaming-daily-extra-ue',
    name: 'Roaming Daily Base Extra UE',
    type: 'daily',
    cost: '35€',
    costUnit: 'giorno',
    description: 'Gettone giornaliero per emergenze o utilizzo occasionale in tutto il mondo.',
    includes: {
      callsOriginated: '30 min (da Extra UE)',
      callsReceived: '30 min (in Extra UE)',
      sms: '60 SMS (da Extra UE)',
      data: '60 MB (in Extra UE)',
    },
    coverage: { type: 'category', category: 'ExtraUE_World' },
    notes: 'Si attiva solo se utilizzata. Utile per connessioni rapide e brevi.',
  },
  {
    id: 'tim-in-nave',
    name: 'TIM in Nave',
    type: 'special',
    cost: 'A consumo',
    costUnit: 'consumo',
    description: 'Tariffe specifiche per quando sei in navigazione su navi da crociera e traghetti.',
    includes: {
      callsOriginated: 'da 1,67€/min + scatto',
      callsReceived: 'da 1,67€/min',
      sms: 'da 49,18 cent/SMS',
      data: 'da 0,216 cent/KB',
    },
    coverage: { type: 'special' },
    notes: "I costi variano in base all'operatore marittimo. Le opzioni roaming standard non sono valide.",
  },
  {
    id: 'tim-in-volo',
    name: 'TIM in Volo',
    type: 'special',
    cost: 'A consumo',
    costUnit: 'consumo',
    description: "Tariffe specifiche per l'utilizzo del telefono in aereo.",
    includes: {
      callsOriginated: '2,75€/min + scatto',
      callsReceived: '2,00€/min',
      sms: '0,45 cent/SMS',
      data: '0,03€/KB',
    },
    coverage: { type: 'special' },
    notes: "Verificare la disponibilità del servizio a bordo. Le opzioni roaming standard non sono valide.",
  },
];