import type { Country, Option } from './types';

export const ALL_COUNTRIES: Country[] = [
  // EU Countries
  { name: 'Austria', category: 'EU', code: 'at' },
  { name: 'Belgio', category: 'EU', code: 'be' },
  { name: 'Bulgaria', category: 'EU', code: 'bg' },
  { name: 'Cipro', category: 'EU', code: 'cy' },
  { name: 'Croazia', category: 'EU', code: 'hr' },
  { name: 'Danimarca', category: 'EU', code: 'dk' },
  { name: 'Estonia', category: 'EU', code: 'ee' },
  { name: 'Finlandia', category: 'EU', code: 'fi' },
  { name: 'Francia', category: 'EU', code: 'fr' },
  { name: 'Germania', category: 'EU', code: 'de' },
  { name: 'Grecia', category: 'EU', code: 'gr' },
  { name: 'Irlanda', category: 'EU', code: 'ie' },
  { name: 'Islanda', category: 'EU', code: 'is' },
  { name: 'Lettonia', category: 'EU', code: 'lv' },
  { name: 'Liechtenstein', category: 'EU', code: 'li' },
  { name: 'Lituania', category: 'EU', code: 'lt' },
  { name: 'Lussemburgo', category: 'EU', code: 'lu' },
  { name: 'Malta', category: 'EU', code: 'mt' },
  { name: 'Norvegia', category: 'EU', code: 'no' },
  { name: 'Paesi Bassi', category: 'EU', code: 'nl' },
  { name: 'Polonia', category: 'EU', code: 'pl' },
  { name: 'Portogallo', category: 'EU', code: 'pt' },
  { name: 'Regno Unito', category: 'EU', code: 'gb' },
  { name: 'Repubblica Ceca', category: 'EU', code: 'cz' },
  { name: 'Romania', category: 'EU', code: 'ro' },
  { name: 'Slovacchia', category: 'EU', code: 'sk' },
  { name: 'Slovenia', category: 'EU', code: 'si' },
  { name: 'Spagna', category: 'EU', code: 'es' },
  { name: 'Svezia', category: 'EU', code: 'se' },
  { name: 'Svizzera', category: 'EU', code: 'ch' },
  { name: 'Ungheria', category: 'EU', code: 'hu' },

  // USA
  { name: 'Stati Uniti', category: 'USA', code: 'us' },

  // TOP16 Countries (which are also ExtraUE_World)
  { name: 'Argentina', category: 'TOP16', code: 'ar' },
  { name: 'Australia', category: 'TOP16', code: 'au' },
  { name: 'Brasile', category: 'TOP16', code: 'br' },
  { name: 'Canada', category: 'TOP16', code: 'ca' },
  { name: 'Cina', category: 'TOP16', code: 'cn' },
  { name: 'Emirati Arabi Uniti', category: 'TOP16', code: 'ae' },
  { name: 'Giappone', category: 'TOP16', code: 'jp' },
  { name: 'Hong Kong', category: 'TOP16', code: 'hk' },
  { name: 'India', category: 'TOP16', code: 'in' },
  { name: 'Israele', category: 'TOP16', code: 'il' },
  { name: 'Russia', category: 'TOP16', code: 'ru' },
  { name: 'Sud Africa', category: 'TOP16', code: 'za' },
  { name: 'Thailandia', category: 'TOP16', code: 'th' },
  { name: 'Turchia', category: 'TOP16', code: 'tr' },
  { name: 'Ucraina', category: 'TOP16', code: 'ua' },

  // ExtraUE_World
  { name: 'Afghanistan', category: 'ExtraUE_World', code: 'af' },
  { name: 'Albania', category: 'ExtraUE_World', code: 'al' },
  { name: 'Algeria', category: 'ExtraUE_World', code: 'dz' },
  { name: 'Arabia Saudita', category: 'ExtraUE_World', code: 'sa' },
  { name: 'Azerbaijan', category: 'ExtraUE_World', code: 'az' },
  { name: 'Bahrain', category: 'ExtraUE_World', code: 'bh' },
  { name: 'Bangladesh', category: 'ExtraUE_World', code: 'bd' },
  { name: 'Bermuda', category: 'ExtraUE_World', code: 'bm' },
  { name: 'Bolivia', category: 'ExtraUE_World', code: 'bo' },
  { name: 'Botswana', category: 'ExtraUE_World', code: 'bw' },
  { name: 'Chad', category: 'ExtraUE_World', code: 'td' },
  { name: 'Cile', category: 'ExtraUE_World', code: 'cl' },
  { name: 'Colombia', category: 'ExtraUE_World', code: 'co' },
  { name: 'Congo', category: 'ExtraUE_World', code: 'cg' },
  { name: 'Corea del Sud', category: 'ExtraUE_World', code: 'kr' },
  { name: 'Costa Rica', category: 'ExtraUE_World', code: 'cr' },
  { name: 'Cuba', category: 'ExtraUE_World', code: 'cu' },
  { name: 'Ecuador', category: 'ExtraUE_World', code: 'ec' },
  { name: 'Egitto', category: 'ExtraUE_World', code: 'eg' },
  { name: 'El Salvador', category: 'ExtraUE_World', code: 'sv' },
  { name: 'Filippine', category: 'ExtraUE_World', code: 'ph' },
  { name: 'Gambia', category: 'ExtraUE_World', code: 'gm' },
  { name: 'Ghana', category: 'ExtraUE_World', code: 'gh' },
  { name: 'Giordania', category: 'ExtraUE_World', code: 'jo' },
  { name: 'Guatemala', category: 'ExtraUE_World', code: 'gt' },
  { name: 'Indonesia', category: 'ExtraUE_World', code: 'id' },
  { name: 'Kenya', category: 'ExtraUE_World', code: 'ke' },
  { name: 'Kosovo', category: 'ExtraUE_World', code: 'xk' },
  { name: 'Kuwait', category: 'ExtraUE_World', code: 'kw' },
  { name: 'Laos', category: 'ExtraUE_World', code: 'la' },
  { name: 'Lesotho', category: 'ExtraUE_World', code: 'ls' },
  { name: 'Macao', category: 'ExtraUE_World', code: 'mo' },
  { name: 'Maldive', category: 'ExtraUE_World', code: 'mv' },
  { name: 'Malesia', category: 'ExtraUE_World', code: 'my' },
  { name: 'Marocco', category: 'ExtraUE_World', code: 'ma' },
  { name: 'Mauritania', category: 'ExtraUE_World', code: 'mr' },
  { name: 'Mauritius', category: 'ExtraUE_World', code: 'mu' },
  { name: 'Messico', category: 'ExtraUE_World', code: 'mx' },
  { name: 'Montenegro', category: 'ExtraUE_World', code: 'me' },
  { name: 'Namibia', category: 'ExtraUE_World', code: 'na' },
  { name: 'Nepal', category: 'ExtraUE_World', code: 'np' },
  { name: 'Nigeria', category: 'ExtraUE_World', code: 'ng' },
  { name: 'Nuova Zelanda', category: 'ExtraUE_World', code: 'nz' },
  { name: 'Oman', category: 'ExtraUE_World', code: 'om' },
  { name: 'Pakistan', category: 'ExtraUE_World', code: 'pk' },
  { name: 'Panama', category: 'ExtraUE_World', code: 'pa' },
  { name: 'Paraguay', category: 'ExtraUE_World', code: 'py' },
  { name: 'Perù', category: 'ExtraUE_World', code: 'pe' },
  { name: 'Polinesia Francese', category: 'ExtraUE_World', code: 'pf' },
  { name: 'Qatar', category: 'ExtraUE_World', code: 'qa' },
  { name: 'Repubblica Dominicana', category: 'ExtraUE_World', code: 'do' },
  { name: 'Reunion', category: 'ExtraUE_World', code: 're' },
  { name: 'Senegal', category: 'ExtraUE_World', code: 'sn' },
  { name: 'Serbia', category: 'ExtraUE_World', code: 'rs' },
  { name: 'Seychelles', category: 'ExtraUE_World', code: 'sc' },
  { name: 'Singapore', category: 'ExtraUE_World', code: 'sg' },
  { name: 'Somalia', category: 'ExtraUE_World', code: 'so' },
  { name: 'Sri Lanka', category: 'ExtraUE_World', code: 'lk' },
  { name: 'Sud Sudan', category: 'ExtraUE_World', code: 'ss' },
  { name: 'Taiwan', category: 'ExtraUE_World', code: 'tw' },
  { name: 'Tanzania', category: 'ExtraUE_World', code: 'tz' },
  { name: 'Tunisia', category: 'ExtraUE_World', code: 'tn' },
  { name: 'Uganda', category: 'ExtraUE_World', code: 'ug' },
  { name: 'Uruguay', category: 'ExtraUE_World', code: 'uy' },
  { name: 'Uzbekistan', category: 'ExtraUE_World', code: 'uz' },
  { name: 'Venezuela', category: 'ExtraUE_World', code: 've' },
  { name: 'Vietnam', category: 'ExtraUE_World', code: 'vn' },
  
  // Excluded from Roaming Mondo New
  { name: 'Andorra', category: 'Excluded_MondoNew', code: 'ad' },
  { name: 'Burundi', category: 'Excluded_MondoNew', code: 'bi' },
  { name: 'Cambogia', category: 'Excluded_MondoNew', code: 'kh' },
  { name: 'Gibuti', category: 'Excluded_MondoNew', code: 'dj' },
  { name: 'Eritrea', category: 'Excluded_MondoNew', code: 'er' },
  { name: 'Etiopia', category: 'Excluded_MondoNew', code: 'et' },
  { name: 'Groenlandia', category: 'Excluded_MondoNew', code: 'gl' },
  { name: 'Guinea', category: 'Excluded_MondoNew', code: 'gn' },
  { name: 'Guinea Bissau', category: 'Excluded_MondoNew', code: 'gw' },
  { name: 'Guinea Equatoriale', category: 'Excluded_MondoNew', code: 'gq' },
  { name: 'Iran', category: 'Excluded_MondoNew', code: 'ir' },
  { name: 'Isole Far Oer', category: 'Excluded_MondoNew', code: 'fo' },
  { name: 'Kyrgyzstan', category: 'Excluded_MondoNew', code: 'kg' },
  { name: 'Libano', category: 'Excluded_MondoNew', code: 'lb' },
  { name: 'Libia', category: 'Excluded_MondoNew', code: 'ly' },
  { name: 'Madagascar', category: 'Excluded_MondoNew', code: 'mg' },
  { name: 'Malawi', category: 'Excluded_MondoNew', code: 'mw' },
  { name: 'Mozambico', category: 'Excluded_MondoNew', code: 'mz' },
  { name: 'New Caledonia', category: 'Excluded_MondoNew', code: 'nc' },
  { name: 'Palestina', category: 'Excluded_MondoNew', code: 'ps' },
  { name: 'Sudan', category: 'Excluded_MondoNew', code: 'sd' },
  { name: 'Togo', category: 'Excluded_MondoNew', code: 'tg' },
  { name: 'Turkmenistan', category: 'Excluded_MondoNew', code: 'tm' },
  { name: 'Vanuatu', category: 'Excluded_MondoNew', code: 'vu' },
  { name: 'Yemen', category: 'Excluded_MondoNew', code: 'ye' },
  { name: 'Zambia', category: 'Excluded_MondoNew', code: 'zm' },
  { name: 'Zimbabwe', category: 'Excluded_MondoNew', code: 'zw' },
];

export const ALL_OPTIONS: Option[] = [
  {
    id: 'tim-stati-uniti',
    name: 'TIM Stati Uniti',
    type: 'monthly',
    cost: '12€',
    costUnit: 'mese',
    description: "L'opzione ideale e più conveniente per i tuoi viaggi di lavoro negli USA.",
    includes: {
      callsOriginated: 'Illimitate (da USA verso USA, Europa e Italia)',
      callsReceived: 'Illimitate (in USA)',
      sms: 'Illimitati (da USA)',
      data: '5 GB (in USA)',
      internationalCalls: "1000 minuti (dall'Italia verso USA)",
    },
    coverage: { type: 'category', category: 'USA' },
    notes: 'Prezzo in promozione, anziché 30€/mese. Overfranchigia dati molto bassa.',
    isRecommended: true,
  },
  {
    id: 'roaming-monthly-top',
    name: 'Roaming Monthly TOP',
    type: 'monthly',
    cost: '35€',
    costUnit: 'mese',
    description: 'Copertura mensile completa per i 16 paesi Extra UE più frequentati.',
    includes: {
      callsOriginated: 'Illimitate (dai 16 Paesi verso i 16 Paesi e Italia). Es: Chiami dalla Cina verso un numero italiano o australiano.',
      callsReceived: 'Illimitate (nei 16 Paesi)',
      sms: 'Illimitati (dai 16 Paesi)',
      data: '5 GB (nei 16 Paesi). Es: Usi la navigazione GPS in Canada.',
      internationalCalls: "1000 minuti (dall'Italia verso i 16 Paesi). Es: Chiami dall'Italia verso un numero in Brasile.",
    },
    coverage: { type: 'category', category: 'TOP16' },
    notes: 'Paesi inclusi: Argentina, Australia, Brasile, Canada, Cina, Emirati Arabi Uniti, Giappone, Hong Kong, India, Israele, Russia, Stati Uniti, Sud Africa, Thailandia, Turchia, Ucraina.',
    isRecommended: true,
  },
  {
    id: 'roaming-mondo-new',
    name: 'Roaming Mondo New',
    type: 'monthly',
    cost: '50€',
    costUnit: 'mese',
    description: 'Copertura mensile per la maggior parte dei paesi Extra UE.',
    includes: {
      callsOriginated: "500 min (da Extra UE verso tutto il Mondo). Es: Chiami dalle Filippine verso l'Italia.",
      callsReceived: '500 min (in Extra UE)',
      sms: '500 SMS (da Extra UE)',
      data: '5 GB (in Extra UE). Es: Navighi su internet in Indonesia.',
    },
    coverage: { type: 'category', category: 'ExtraUE_World' },
    notes: 'Esclude una lista specifica di paesi e il traffico satellitare/marittimo/in volo. Ideale per viaggi multi-paese fuori dalle zone TOP.',
  },
  {
    id: 'executive-class-2-0',
    name: 'Executive Class 2.0',
    type: 'weekly',
    cost: '40€',
    costUnit: 'settimana',
    description: 'Opzione flessibile con canone mensile per chiamate internazionali e un gettone settimanale che si attiva solo quando sei in Extra UE.',
    includes: {
      callsOriginated: '500 min/settimana (da Extra UE verso tutto il Mondo). Es: Sei in Indonesia e chiami un cliente nelle Filippine.',
      callsReceived: '500 min/settimana (in Extra UE)',
      sms: '1000 SMS/settimana (in Extra UE)',
      data: '2 GB/settimana (in Extra UE)',
      internationalCalls: 'Canone fisso mensile (30€) include: 1000 min/mese da Italia vs Mondo e 1000 min/mese da UE vs Extra UE. Es: Chiami dall\'ufficio in Italia verso un fornitore in Marocco.',
    },
    coverage: { type: 'category', category: 'ExtraUE_World' },
    notes: "Il gettone settimanale da 40€ si attiva automaticamente al primo utilizzo (chiamata, SMS, dati) in un paese Extra UE e dura 7 giorni.",
  },
  {
    id: 'roaming-weekly-top',
    name: 'Roaming Weekly TOP',
    type: 'weekly',
    cost: '35€',
    costUnit: 'settimana',
    description: 'Gettone settimanale per i 16 paesi Extra UE più frequentati.',
    includes: {
      callsOriginated: '250 min (dai 16 Paesi)',
      callsReceived: '250 min (nei 16 Paesi)',
      sms: '500 SMS (dai 16 Paesi)',
      data: '500 MB (nei 16 Paesi)',
    },
    coverage: { type: 'category', category: 'TOP16' },
    notes: 'Si attiva solo se utilizzata. Paesi inclusi: Argentina, Australia, Brasile, Canada, Cina, Emirati Arabi Uniti, Giappone, Hong Kong, India, Israele, Russia, Stati Uniti, Sud Africa, Thailandia, Turchia, Ucraina.',
  },
  {
    id: 'roaming-daily-extra-ue',
    name: 'Roaming Daily Base Extra UE',
    type: 'daily',
    cost: '35€',
    costUnit: 'giorno',
    description: 'Gettone giornaliero per emergenze o utilizzo occasionale in tutto il mondo.',
    includes: {
      callsOriginated: '30 min (da Extra UE)',
      callsReceived: '30 min (in Extra UE)',
      sms: '60 SMS (da Extra UE)',
      data: '60 MB (in Extra UE)',
    },
    coverage: { type: 'category', category: 'ExtraUE_World' },
    notes: 'Si attiva solo se utilizzata. Utile per connessioni rapide e brevi.',
  },
  {
    id: 'tim-in-nave',
    name: 'TIM in Nave',
    type: 'special',
    cost: 'A consumo',
    costUnit: 'consumo',
    description: 'Tariffe specifiche per quando sei in navigazione su navi da crociera e traghetti.',
    includes: {
      callsOriginated: 'da 1,67€/min + scatto',
      callsReceived: 'da 1,67€/min',
      sms: 'da 49,18 cent/SMS',
      data: 'da 0,216 cent/KB',
    },
    coverage: { type: 'special' },
    notes: "I costi variano in base all'operatore marittimo. Le opzioni roaming standard non sono valide.",
  },
  {
    id: 'tim-in-volo',
    name: 'TIM in Volo',
    type: 'special',
    cost: 'A consumo',
    costUnit: 'consumo',
    description: "Tariffe specifiche per l'utilizzo del telefono in aereo.",
    includes: {
      callsOriginated: '2,75€/min + scatto',
      callsReceived: '2,00€/min',
      sms: '0,45 cent/SMS',
      data: '0,03€/KB',
    },
    coverage: { type: 'special' },
    notes: "Verificare la disponibilità del servizio a bordo. Le opzioni roaming standard non sono valide.",
  },
];